//undefs.h
//
#undef void
#undef linux
#undef windows
#undef other
#undef ST_EVE_ST_ED
#undef ST_SYSTYPE
#undef ST_ALL
#undef ST_FULLSCR
#undef ST_ST_CARG
#undef ST_ST_WARG
#undef ST_ST_ECARG
#undef ST_ST_FARG
#undef ST_ST_SCARG
#undef ST_ST_END
#undef ST_SYSTYPE
#undef ST_ST_TYPE
#undef ST_SYSTEMF
#undef ST_FOPENF
#undef ST_SCANPWD
#undef ST_FILEPART
#undef ST_MLC
#undef ST_ST_TRYDONTUSEWINMAIN
#undef ST_INTPSF
#undef ST_COPY
#undef ST_BOMB
#undef STEST_ON 
#undef UN_STEST
#undef UN_ST_ST
#undef STESTMG_ON
#undef aline
#undef nesebg
#undef neseed
#undef stelib
#undef stearg
#undef efolat
#undef elimits
#undef stebool
#undef estring
#undef esignal
#undef steio
#undef cocpio
#undef etype
#undef emlc
#undef emath
#undef elocale
#undef ewchar
#undef sterrno
#undef usingstd
#undef usingste
#undef stcocp
#undef stcocp_
#undef cocpfio
#undef cppstring
#undef cocpsio
//
